// generated by "sampctl package init"
#include <a_samp>

#define YSI_NO_HEAP_MALLOC

#include "better-geo.inc"

main() 
{
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
}

public OnPlayerConnect(playerid)
{
	inline OnGeoResults(GeoResults:result)
	{
		if (!IsValidGeoResults(result))
		{
			printf("Unable to give results to %d", playerid);
			return 0;
		}

		new string:countryName[32], string:ispName[32];
		Geo_GetCountryName(result, countryName);
		Geo_GetISPName(result, ispName);

		va_SendClientMessage(playerid, 0xFFFFFFAA, "LOGIN: %s is logged-in to the server [%s | %s]", ReturnPlayerName(playerid), countryName, ispName);
	}

	Geo_CheckPlayer(
		playerid, 
		using inline OnGeoResults, 
		OPTION_IP_RESULTS | OPTION_COUNTRY_NAME | OPTION_ISP_NAME
	);
	return 1;
}
