// generated by "sampctl package init"
#include <a_samp>

#define YSI_NO_HEAP_MALLOC

#include "better-geo.inc"

main() 
{
	inline OnGeoResults(GeoResults:result)
	{
		if (!IsValidGeoResults(result))
		{
			print("Unable to give the results");
			return;
		}

		new 
			string:ipResults[16 + 1],
			string:countryName[32], 
			string:ispName[32];

		Geo_GetIpResults(result, ipResults);
		Geo_GetCountryName(result, countryName);
		Geo_GetISPName(result, ispName);

		printf("This %s is from %s using %s ISP's", ipResults, countryName, ispName);
	}

	Geo_CheckIpAddress("24.48.0.1", using inline OnGeoResults);
}

